# Generated by Django 5.2.2 on 2025-06-10 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_historia_itemhistoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='historia',
            name='musica_youtube',
            field=models.URLField(blank=True, null=True, verbose_name='Link da música do YouTube'),
        ),
    ]
