# Generated by Django 5.2.2 on 2025-06-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_historia_musica_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Determina se o usuário tem privilégios de administrador.', verbose_name='é administrador'),
        ),
    ]
