# Generated by Django 5.2.2 on 2025-06-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='texto_inicio',
            field=models.TextField(blank=True, help_text='Texto personalizado para exibir na tela inicial.', null=True, verbose_name='texto de início'),
        ),
    ]
