# Generated by Django 5.2.2 on 2025-06-11 14:48

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_texto_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemhistoria',
            name='foto',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='historias_fotos/'),
        ),
    ]
